name: mlops-example-tensorflow-

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python dependencies and train model
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          python model.py


